name: voron-simulation-stack
services:
  klipper:
    image: ghcr.io/zer0bit/docker-klipper-simulavr:latest
    container_name: klipper
    hostname: klipper
    restart: unless-stopped
    volumes:
      - ${STORAGE_ROOT}/klipper:/config
    environment:
      - MCU=simulavr
    networks:
      - printer_net

  moonraker:
    image: arksine/moonraker:latest
    container_name: moonraker
    hostname: moonraker
    restart: unless-stopped
    depends_on:
      - klipper
    volumes:
      - ${STORAGE_ROOT}/moonraker:/config
    environment:
      - KLIPPER_HOST=klipper
      - KLIPPER_PORT=7125
    networks:
      - printer_net

  mainsail:
    image: mainsail/mainsail:latest
    container_name: mainsail
    hostname: mainsail
    restart: unless-stopped
    depends_on:
      - moonraker
    ports:
      - "80:80"
    environment:
      - MOONRAKER_API=http://moonraker:7125
    networks:
      - printer_net

networks:
  printer_net:
    driver: bridge
