server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://metrics.home.arpa:3100/loki/api/v1/push

scrape_configs:
  - job_name: klippy
    static_configs:
      - targets: [localhost]
        labels:
          job: klippy
          host: voron-printer
          __path__: /home/poindexter12/printer_data/logs/klippy.log
  - job_name: journal
    journal:
      max_age: 12h
      labels:
        host: voron-printer
    relabel_configs:
      - source_labels: ['__journal__transport']
        target_label: transport
      - source_labels: ['__journal__transport']
        regex: kernel
        target_label: job
        replacement: kernel
      - source_labels: ['__journal__systemd_unit']
        target_label: unit
      - source_labels: ['__journal__systemd_unit']
        regex: '(klipper|moonraker|crowsnest)\.service'
        target_label: job
        replacement: services
